// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.6
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"basic",prev:"",next:"",duration:20*100,delay:20*100,width:726,height:340,autoPlay:true,autoPlayVideo:false,playPause:true,stopOnHover:false,loop:false,bullets:0,caption:false,captionEffect:"none",controls:true,controlsThumb:["data1/tooltips/banner1.jpg", "data1/tooltips/banner2.jpg", "data1/tooltips/banner3.jpg", "data1/tooltips/banner4.jpg", "data1/tooltips/banner5.jpg", "data1/tooltips/banner6.jpg", "data1/tooltips/banner7.jpg"],responsive:1,fullScreen:false,gestures:2,onBeforeStep:0,images:[{src:"./banner1.jpg",title:"banner1"},{src:"./banner2.jpg",title:"banner2"},{src:"./banner3.jpg",title:"banner3"},{src:"./banner4.jpg",title:"banner4"},{src:"./banner5.jpg",title:"banner5"},{src:"./banner6.jpg",title:"banner6",href:"http://wowslider.com"},{src:"./banner7.jpg",title:"banner7"}]});